In [4]:
# indexing and slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[3]

3

In [6]:
arr[3:7]

array([3, 4, 5, 6])

In [9]:
arr[:3] 

array([0, 1, 2])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:4]=100
arr
# not possible in lists

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [11]:
arr=np.arange(11)

In [13]:
sliced_arr=arr[0:5]
sliced_arr

array([0, 1, 2, 3, 4])

In [16]:
sliced_arr[:]=22 # put " : " for selecting everything


In [17]:
sliced_arr

array([22, 22, 22, 22, 22])

In [19]:
arr
# effecting the original arr even it is stored seperate variable

array([22, 22, 22, 22, 22,  5,  6,  7,  8,  9, 10])

In [20]:
# for this case we shld use .copy()

In [21]:
arr=np.arange(11)

In [23]:
arr_cpy=arr.copy()

In [24]:
arr_cpy[:]=100

In [26]:
# it doesnt change anything
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr_2d=np.arange(9).reshape(3,3)

In [30]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr_2d[2][0]
# row in 1st bracket and column in 2nd

6

In [33]:
#similarly
arr_2d[2,0]

6

In [34]:
arr_2d[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
arr_2d[2:]

array([[6, 7, 8]])

In [38]:
#for extracting sub matrix
arr_2d[1:,1:]

array([[4, 5],
       [7, 8]])

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [42]:
bool_arr = arr>3
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [44]:
arr[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [45]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [46]:
total_rolls_over_two=dice_rolls>2


In [47]:
len(total_rolls_over_two)

29