In [8]:
# operations

In [1]:
import numpy as np

In [2]:
arr =np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [6]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# in bulit math libraries
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
arr.sum()

45

In [12]:
arr.max()

9

In [13]:
arr.var()

8.25

In [14]:
arr.std()

2.8722813232690143

In [15]:
# incase of 2d arrays

In [16]:
arr2d=np.arange(9).reshape(3,3)

In [19]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr2d.sum(axis=0)
# sum along row

array([ 9, 12, 15])

In [22]:
arr2d.sum(axis=1)
# along column

array([ 3, 12, 21])