In [1]:
import numpy as np 

In [2]:
np.array=[1,2,3,4]

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,9,3)

array([0. , 4.5, 9. ])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
random=np.random.rand(11)
random


array([0.4077682 , 0.12950155, 0.33575518, 0.70165201, 0.76079588,
       0.32979813, 0.34572391, 0.12918314, 0.26950439, 0.51936641,
       0.05187221])

In [21]:
np.random.rand(5,2)

array([[0.84222756, 0.62406623],
       [0.67034786, 0.8176599 ],
       [0.46563835, 0.96586039],
       [0.80944789, 0.99061771],
       [0.17459348, 0.81952722]])

In [23]:
np.random.randn(5,2)

array([[ 1.13495118,  0.41602797],
       [ 0.37576781, -0.71058954],
       [-3.10069687,  0.21999574],
       [ 1.10119737, -0.10256796],
       [ 0.40402505,  1.26385609]])

In [28]:
np.random.seed(42)
# it sets a set of random numbers

In [29]:
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [30]:
np.random.seed(50)
np.random.rand(10)

array([0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ,
       0.99657423, 0.4081972 , 0.77189399, 0.76053669, 0.31000935])

In [31]:
np.random.seed(50)
np.random.rand(10)
# same outputs for differenet numbers

array([0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ,
       0.99657423, 0.4081972 , 0.77189399, 0.76053669, 0.31000935])

In [36]:
arr2=np.arange(0,100,10)

In [37]:
len(arr2)

10

In [38]:
arr2.max()

90

In [39]:
arr2.min()

0

In [42]:
arr2.argmax() # position of max number in arr2

9

In [43]:
arr2.dtype

dtype('int64')

In [44]:
type(arr2)

numpy.ndarray

In [49]:
arr2.shape #shape of array

(10,)

In [50]:
arr2.size # no.of elements in an array

10

In [52]:
myarray=np.linspace(0,10,101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])